import {
  AlertTriangle,
  BarChart3,
  Brain,
  Briefcase,
  CalendarCheck,
  CheckCircle,
  CircleHelp,
  CircleOff,
  CircleX,
  ClipboardCheck,
  ClipboardList,
  Clock,
  Construction,
  Crown,
  Eye,
  FileSearch,
  Flame,
  FlaskConical,
  HandHelping,
  Handshake,
  HeartCrack,
  HelpCircle,
  ListChecks,
  MessageSquare,
  MinusCircle,
  MonitorSmartphone,
  PenLine,
  PlayCircle,
  Puzzle,
  Rocket,
  Scale,
  Settings,
  Sparkles,
  Table2,
  Timer,
  UserX,
  Users,
  Wrench,
  XCircle,
  Zap,
  type LucideIcon,
} from 'lucide-react'

export const quizIconMap: Record<string, LucideIcon> = {
  'alert-triangle': AlertTriangle,
  'bar-chart-3': BarChart3,
  brain: Brain,
  briefcase: Briefcase,
  'calendar-check': CalendarCheck,
  'check-circle': CheckCircle,
  'circle-help': CircleHelp,
  'circle-off': CircleOff,
  'circle-x': CircleX,
  'clipboard-check': ClipboardCheck,
  'clipboard-list': ClipboardList,
  clock: Clock,
  construction: Construction,
  crown: Crown,
  eye: Eye,
  'file-search': FileSearch,
  flame: Flame,
  'flask-conical': FlaskConical,
  'hand-helping': HandHelping,
  handshake: Handshake,
  'heart-crack': HeartCrack,
  'help-circle': HelpCircle,
  'list-checks': ListChecks,
  'message-square': MessageSquare,
  'minus-circle': MinusCircle,
  'monitor-smartphone': MonitorSmartphone,
  'pen-line': PenLine,
  'play-circle': PlayCircle,
  puzzle: Puzzle,
  rocket: Rocket,
  scale: Scale,
  settings: Settings,
  sparkles: Sparkles,
  'table-2': Table2,
  timer: Timer,
  'user-x': UserX,
  users: Users,
  wrench: Wrench,
  'x-circle': XCircle,
  zap: Zap,
}
